# Generated by Django 5.1.4 on 2025-04-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='twitter',
        ),
    ]
