# Generated by Django 5.1.4 on 2025-04-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_remove_testimonial_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
