# Generated by Django 5.1.4 on 2025-04-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_alter_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name2', models.CharField(max_length=200)),
                ('Email2', models.CharField(max_length=200)),
                ('Subject2', models.CharField(max_length=200)),
                ('phone2', models.CharField(max_length=200)),
                ('Message2', models.TextField(max_length=1500)),
            ],
        ),
    ]
