# Generated by Django 5.1.4 on 2025-04-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('surgery', models.CharField(choices=[('laparoscopic', 'Laparoscopic Surgery'), ('hernia', 'Hernia'), ('stapler', 'Stapler Surgery'), ('proctology', 'Proctology'), ('acroantics', 'Acroantics Surgery'), ('breast', 'Breast Surgery')], max_length=50)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
